# Generated by Django 2.2.3 on 2019-10-26 14:27

from django.db import migrations, models
import myblog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to=myblog.models.image_path)),
            ],
        ),
    ]
