# Generated by Django 2.2.3 on 2019-10-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20191026_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='number_of_reads',
            field=models.IntegerField(default=0),
        ),
    ]
